DELETE FROM STOCK;
DELETE FROM ORDER_DETAIL;
DELETE FROM ORDER_TABLE;
DELETE FROM PRODUCT;
DELETE FROM PRODUCT_CATEGORY;
DELETE FROM SUPPLIER;
DELETE FROM CUSTOMER;
DELETE FROM LOCATION;
DELETE FROM ADDRESS;

INSERT INTO SUPPLIER VALUES (100, 'Supplier');

-- these insert are for stock and order detail tests
INSERT INTO SUPPLIER VALUES (101, 'Supplier');
INSERT INTO PRODUCT_CATEGORY VALUES (100, 'PC', 'PCDescription');
INSERT INTO PRODUCT VALUES (100, 'Product', 'ProductDescription', 1, 1, 100, 101);
INSERT INTO ADDRESS VALUES (100, 'RO', 'CJ', 'CJ', 'STR.');
INSERT INTO ADDRESS VALUES (101, 'DE', 'M', 'M', 'STR.');
INSERT INTO LOCATION VALUES (100, 'Location', 100);
INSERT INTO CUSTOMER VALUES (100, 'CUST', 'OMER', '', 'cc',);
INSERT INTO ORDER_TABLE (ID, SHIPPED_FROM, CUSTOMER, ADDRESS, ORDER_DATE_TIME) VALUES (100, 100, 100, 101, '2000-01-01 23:59:59');

-- these inserts are for single location strategy tests
INSERT INTO SUPPLIER VALUES (201, 'Supplier');
INSERT INTO PRODUCT_CATEGORY VALUES (201, 'PC', 'PCDescription');
INSERT INTO PRODUCT VALUES (201, 'Product 1', 'ProductDescription', 1, 1, 201, 201);
INSERT INTO PRODUCT VALUES (202, 'Product 2', 'ProductDescription', 1, 1, 201, 201);
INSERT INTO PRODUCT VALUES (203, 'Product 3', 'ProductDescription', 1, 1, 201, 201);
INSERT INTO ADDRESS VALUES (201, 'RO', 'Cluj-Napoca', 'CJ', 'Brassai Samuel, 9');
INSERT INTO ADDRESS VALUES (202, 'RO', 'Cluj-Napoca', 'CJ', 'Ciocarliei, 6');
INSERT INTO ADDRESS VALUES (203, 'RO', 'Sfintu-Gheorghe', 'CV', 'Nicolae Iorga, 3');
INSERT INTO ADDRESS VALUES (204, 'RO', 'Miercurea-Ciuc', 'HR', 'Culmei, 14');
INSERT INTO LOCATION VALUES (201, 'Location 1', 201);
INSERT INTO LOCATION VALUES (202, 'Location 2', 202);
INSERT INTO LOCATION VALUES (203, 'Location 3', 203);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (201, 202, 4);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (201, 203, 6);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (202, 201, 10);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (202, 202, 4);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (202, 203, 5);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (203, 201, 5);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (203, 203, 9);
INSERT INTO STOCK (PRODUCT_NUMBER, LOCATION_NUMBER, QUANTITY) VALUES (203, 202, 10);

