DELETE FROM STOCK;
DELETE FROM ORDER_DETAIL;
DELETE FROM ORDER_TABLE;
DELETE FROM PRODUCT;
DELETE FROM PRODUCT_CATEGORY;
DELETE FROM SUPPLIER;
DELETE FROM CUSTOMER;
DELETE FROM LOCATION;
DELETE FROM ADDRESS;

INSERT INTO SUPPLIER VALUES (100, 'Supplier');

-- these insert are for stock and order detail tests
INSERT INTO SUPPLIER VALUES (101, 'Supplier');
INSERT INTO PRODUCT_CATEGORY VALUES (100, 'PC', 'PCDescription');
INSERT INTO PRODUCT VALUES (100, 'Product', 'ProductDescription', 1, 1, 100, 101);
INSERT INTO ADDRESS VALUES (100, 'RO', 'CJ', 'CJ', 'STR.');
INSERT INTO ADDRESS VALUES (101, 'DE', 'M', 'M', 'STR.');
INSERT INTO LOCATION VALUES (100, 'Location', 100);
INSERT INTO CUSTOMER VALUES (100, 'CUST', 'OMER', 'cc');
INSERT INTO ORDER_TABLE VALUES (100, 101, 100, 100);
