DROP SCHEMA IF EXISTS MY_APP;

CREATE SCHEMA MY_APP;

CREATE TABLE MY_APP.SUPPLIER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
);

create sequence supplier_sequence start with 1 increment by 1;

INSERT INTO MY_APP.SUPPLIER VALUES (1, 'TEST');
